# Generated by Django 4.1 on 2022-09-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
