# Generated by Django 4.1 on 2022-09-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0003_product_category_alter_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_app.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
