# Generated by Django 4.1 on 2022-09-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0004_remove_product_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
