# Generated by Django 4.1 on 2022-09-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length='250')),
                ('image', models.ImageField(upload_to='deals')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ('name',),
            },
        ),
    ]
