# Generated by Django 4.1 on 2022-09-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0007_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='slug',
        ),
    ]
